name: CodeParser
options:
  bundleIdPrefix: com.codeparser
  deploymentTarget:
    iOS: "17.0"
    macOS: "14.0"
  developmentLanguage: en
  xcodeVersion: "16.0"

settings:
  SWIFT_VERSION: "6.0"
  IPHONEOS_DEPLOYMENT_TARGET: "17.0"
  MACOSX_DEPLOYMENT_TARGET: "14.0"

targets:
  CodeParser:
    type: framework
    supportedDestinations: [iOS, macOS]
    sources:
      - path: Sources/CodeParser
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.codeparser.CodeParser
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "6.0"
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_CFBundleDisplayName: CodeParser
        DEFINES_MODULE: true
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        Release:
          SWIFT_COMPILATION_MODE: wholemodule

  CodeParserShowCase:
    type: application
    platform: auto
    supportedDestinations: [iOS, macOS]
    sources:
      - path: Sources/CodeParserShowCase
    dependencies:
      - target: CodeParser
        destinationFilter: [iOS, macOS]
    schemes:
      run:
        config: Debug
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.codeparser.CodeParserShowCase
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "6.0"
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_CFBundleDisplayName: CodeParser ShowCase
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.developer-tools
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        Release:
          SWIFT_COMPILATION_MODE: wholemodule

  CodeParserTests:
    type: bundle.unit-test
    supportedDestinations: [iOS, macOS]
    sources:
      - path: Tests/CodeParserTests
    dependencies:
      - target: CodeParser
        destinationFilter: [iOS, macOS]
      - target: CodeParserShowCase
        destinationFilter: [iOS, macOS]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.codeparser.CodeParserTests
        SWIFT_VERSION: "6.0"
        GENERATE_INFOPLIST_FILE: true

  CodeParserShowCaseTests:
    type: bundle.unit-test
    supportedDestinations: [iOS, macOS]
    sources:
      - path: Tests/CodeParserShowCaseTests
    dependencies:
      - target: CodeParser
        destinationFilter: [iOS, macOS]
      - target: CodeParserShowCase
        destinationFilter: [iOS, macOS]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.codeparser.CodeParserShowCaseTests
        SWIFT_VERSION: "6.0"
        GENERATE_INFOPLIST_FILE: true
